export const actionTypes = 
  {
    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
    ADD_POST: 'ADD_POST',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    FETCH_COMMENTS_SUCCESS: 'FETCH__COMMENTS_SUCCESS',
    FETCH_COMMENTS_ERROR: 'FETCH__COMMENTS_ERROR'  
  }